# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20161213_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_client',
            field=models.BooleanField(default=True, verbose_name='is_client'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='is_superuser'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_washr',
            field=models.BooleanField(default=False, verbose_name='is_washr'),
        ),
    ]
